### ISSUE TITLE
Some questions about training

### ISSUE THREAD

**Issue by ChengkaiYang** [Alan-LanFeng/UniTraj#1]
Hello, Alan:
      I have just found your excellent work to combine all of AD datasets together! In your paper, you mentioned evaluating on Nuscenes evaluation dataset after training on Nuscenes training dataset.(In the picture the brier-minFDE is 3.36). I want to train and get the result on my device.Could you please told me details about this experiment?
      
<img width="715" alt="image" src="https://github.com/Alan-LanFeng/UniTraj/assets/71952712/1aeac638-986e-4ae2-bb01-f9d1a892874f">
      1. I found that in config file 'config.yaml', 'train_data_path' and 'val_data_path' are set the same. Is the brier-minFDE result 3.36 got at this settings or you have splited train and val datasets to get the result 3.36?
      I would appreciate if you can help me!

**Comment by Alan-LanFeng** [comment]
Hi, please go to our official repo for detailed information, thanks! https://github.com/vita-epfl/UniTraj
